name: Required Status

on:
  pull_request:
  push:
    branches:
      - "trunk-merge/**"

permissions:
  contents: read

jobs:
  required-status:
    name: Required Status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 2

      - name: Check changed files for whitespace errors
        run: git diff --check HEAD^ HEAD
